export const faqs = [
  {
    id: 1,
    title: "Registration Fees",
    answer:
      "The registration fee varies by event. Some events are free, while others may require a fee. Check the event details on our website for specific pricing and payment options.",
  },
  {
    id: 2,
    title: "Registration Deadlines",
    answer:
      "Each event has a specific registration deadline mentioned on our website. Some events have limited slots, so early registration is recommended to secure your spot.",
  },
  {
    id: 3,
    title: "Prizes & Awards",
    answer:
      "Prizes vary by event and may include cash rewards, certificates, trophies, and exclusive goodies. Details are available on our website.",
  },
  {
    id: 4,
    title: "Contacting Organizers",
    answer:
      "For any queries, you can reach out to event organizers through the contact details provided on our website. You can also follow our official social media pages for updates and announcements.",
  },
  {
    id: 5,
    title: "How to Register",
    answer:
      "To register, visit the official Meraki website or our Instagram page. Select your desired event and follow the registration steps. Ensure you provide correct details to confirm your participation.",
  },
  {
    id: 6,
    title: "Eligibility & Requirements",
    answer:
      "Some events may require specific technical skills or knowledge of particular tools, while others are open to all. Please check the event description for details before registering.",
  },
  {
    id: 7,
    title: "Preparation Guidelines",
    answer:
      "Preparation depends on the event type. Some require knowledge of specific software, coding skills, or technical expertise, while others focus on creativity and teamwork. Check the event guidelines on our website for details.",
  },
  {
    id: 8,
    title: "Participation Rules",
    answer:
      "There is no limit to the number of events you can participate in. However, ensure there are no scheduling conflicts, as you must be present for each event you register for.",
  },
];

export const cardsData = [
  {
    id: "1",
    name: "Stock Buzz",
    overview:
      "An exciting event integrating a compelling story with a virtual stock market simulation where teams strategize trades based on an unfolding narrative.",
    image: "/events/event8.png",
    date: "2nd April 2025",
    time: "1:30 pm – 5:00 pm",
    regDate: "30th March 2025",
    club: "AAVESH",
    interIIIT: "No",
    teamLimit: "2-3 members per team",
    tag: ["stock market", "trading", "simulation"],
    difficulty: "Strategic",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/p/stock-buzz-indian-institute-of-information-technology-iiit-una-1433470",
  },
  {
    id: "2",
    name: "Money Heist",
    overview:
      "A high-stakes challenge where teams assemble a crew, plan a bank heist, and overcome obstacles like hostage negotiations and police raids to escape with the most money.",
    image: "/images/backgrounds/event.png",
    date: "2nd April 2025",
    time: "5:00 pm - 7:30 pm",
    regDate: "30th March 2025",
    club: "MERAKI",
    interIIIT: "No",
    teamLimit: "4-6 members per team",
    tag: ["heist", "strategy", "competition"],
    difficulty: "Extreme",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/event/money-heist",
  },
  {
    id: "3",
    name: "Coderation",
    overview:
      "A competitive programming contest where participants solve algorithmic challenges on lab PCs under time constraints with live ranking updates.",
    image: "/events/event9.png",
    date: "2nd April 2025",
    time: "7:30 pm - 9:00 pm",
    regDate: "29th March 2025",
    club: "FORCE",
    interIIIT: "No",
    teamLimit: "Individual",
    tag: ["coding", "programming", "algorithms"],
    difficulty: "Competitive",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/p/coderation-indian-institute-of-information-technology-iiit-una-1433761",
  },
  {
    id: "4",
    name: "Prog-o-thon",
    overview:
      "A dynamic hackathon challenging teams to conceptualize, design, and develop innovative projects over 2 nights and 1 day, culminating in a presentation.",
    image: "/events/event1.png",
    date: "2nd & 3rd April 2025",
    time: "9:00 pm onwards",
    regDate: "28th March 2025",
    club: "FORCE",
    interIIIT: "Yes",
    teamLimit: "3 members per team",
    tag: ["hackathon", "innovation", "coding"],
    difficulty: "Intense",
    prizePool: "₹10,000 + Trophies & Goodies",
    unstopLink: "https://unstop.com/hackathons/progothon-indian-institute-of-information-technology-iiit-una-1433809",
  },
  {
    id: "5",
    name: "NoScope",
    overview:
      "The annual esports fest featuring competitive gaming across titles like BGMI, Valorant, FIFA, Clash of Clans, and Mini Militia – offering a professional tournament experience.",
    image: "/images/backgrounds/event.png",
    date: "1st - 4th April 2025",
    time: "9:30 pm onwards",
    regDate: "31st March 2025",
    club: "EPMOC",
    interIIIT: "Yes",
    teamLimit: "Varies per game",
    tag: ["esports", "gaming", "competition"],
    difficulty: "High-Octane",
    prizePool: "₹5,000 + Trophies & Goodies",
    unstopLink: "https://unstop.com/event/noscope",
  },
  {
    id: "6",
    name: "Ad-Venture",
    overview:
      "A creative advertising competition where teams design and present unique ads for assigned products or themes, judged on originality and engagement.",
    image: "/events/event10.png",
    date: "3rd April 2025",
    time: "10:30 am - 1:00 pm",
    regDate: "1st April 2025",
    club: "MERAKI",
    interIIIT: "No",
    teamLimit: "3 members per team",
    tag: ["advertising", "creativity", "presentation"],
    difficulty: "Creative",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/event/ad-venture",
  },
  {
    id: "7",
    name: "Ard-Win-O",
    overview:
      "A technical event challenging participants to build a functional project using Arduino Uno and sensors, following a quiz qualifier round.",
    image: "/events/event11.png",
    date: "3rd April 2025",
    time: "10:30 am - 1:00 pm",
    regDate: "30th March 2025",
    club: "AAVESH",
    interIIIT: "No",
    teamLimit: "3-4 members per team",
    tag: ["electronics", "arduino", "innovation"],
    difficulty: "Tech-Savvy",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/p/ard-win-o-meraki-25-indian-institute-of-information-technology-iiit-una-1432581 ",
  },
  {
    id: "8",
    name: "Hack-The-Flag",
    overview:
      "A competitive Capture The Flag event testing cybersecurity skills with challenges in cryptography, reverse engineering, web exploitation, and forensics.",
    image: "/images/backgrounds/event.png",
    date: "3rd April 2025",
    time: "1:45 pm - 5:30 pm",
    regDate: "30th March 2025",
    club: "AAVESH",
    interIIIT: "No",
    teamLimit: "2-3 members per team",
    tag: ["cybersecurity", "CTF", "challenges"],
    difficulty: "High-Stakes",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/event/hack-the-flag",
  },
  {
    id: "9",
    name: "Sold Mold",
    overview:
      "A soldering challenge where teams identify a faulty component, select a circuit, and implement it on a PCB as quickly as possible.",
    image: "/events/event12.png",
    date: "3rd April 2025",
    time: "1:45 pm - 5:30 pm",
    regDate: "30th March 2025",
    club: "AAVESH",
    interIIIT: "Yes",
    teamLimit: "3 members per team",
    tag: ["soldering", "electronics", "hardware"],
    difficulty: "Technical",
    prizePool: "₹5,000 + Trophies & Goodies",
    unstopLink: "https://unstop.com/p/sold-mold-indian-institute-of-information-technology-iiit-una-1434588",
  },
  {
    id: "10",
    name: "Run Code Run",
    overview:
      "A competitive coding contest where teams solve multiple programming challenges while facing random eliminations and strategic QR code immunity rounds.",
    image: "/events/event4.png",
    date: "3rd April 2025",
    time: "6:00 pm - 8:30 pm",
    regDate: "31st March 2025",
    club: "FORCE",
    interIIIT: "Yes",
    teamLimit: "3 members per team",
    tag: ["coding", "programming", "strategy"],
    difficulty: "Extreme",
    prizePool: "₹5,000 + Trophies & Goodies",
    unstopLink: "https://unstop.com/hackathons/run-code-run-indian-institute-of-information-technology-iiit-una-1435143",
  },
  {
    id: "11",
    name: "Tech Debate",
    overview:
      "A debate competition where teams discuss tech-related topics, presenting opening statements, counter-arguments, and concluding remarks to persuade the judges.",
    image: "/events/event13.png",
    date: "4th April 2025",
    time: "10:45 am - 1:00 pm",
    regDate: "31st March 2025",
    club: "AAVESH",
    interIIIT: "No",
    teamLimit: "3 members per team",
    tag: ["debate", "communication", "tech"],
    difficulty: "Intense",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/p/tech-debate-indian-institute-of-information-technology-iiit-una-1433760",
  },
  {
    id: "12",
    name: "IPL Auction",
    overview:
      "A high-stakes virtual auction event where teams bid in real time using a set budget to build the best cricket squad.",
    image: "/events/event14.png",
    date: "4th April 2025",
    time: "10:45 am - 1:00 pm",
    regDate: "31st March 2025",
    club: "MERAKI",
    interIIIT: "No",
    teamLimit: "Team-based",
    tag: ["auction", "cricket", "strategy"],
    difficulty: "Competitive",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/event/ipl-auction",
  },
  {
    id: "13",
    name: "Mystery Ops",
    overview:
      "An immersive escape-room style challenge where teams navigate through themed rooms, solving puzzles and challenges to advance and win.",
    image: "/events/event7.png",
    date: "4th April 2025",
    time: "1:30 pm - 2:45 pm",
    regDate: "31st March 2025",
    club: "AAVESH",
    interIIIT: "No",
    teamLimit: "2-4 members per team",
    tag: ["Escape room", "Mystery", "Challenge"],
    difficulty: "Mysterious",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/competitions/mystery-ops-indian-institute-of-information-technology-iiit-una-1434611",
  },
  {
    id: "14",
    name: "Scales Quest",
    overview:
      "A two-round event combining a pen-and-paper quiz with a virtual snakes and ladders challenge, testing knowledge and strategic thinking.",
    image: "/events/event15.png",
    date: "4th April 2025",
    time: "3:00 pm - 5:30 pm",
    regDate: "31st March 2025",
    club: "AAVESH",
    interIIIT: "No",
    teamLimit: "4 members per team",
    tag: ["quiz", "strategy", "game"],
    difficulty: "Brainstorming",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/o/wcJhAZR?lb=rpKpLz37",
  },
  {
    id: "15",
    name: "Hired or Fired?",
    overview:
      "A recruitment challenge featuring coding, aptitude, and mock interview rounds designed to test individual problem-solving and technical skills.",
    image: "/events/event16.png",
    date: "4th April 2025",
    time: "3:00 pm - 5:30 pm",
    regDate: "31st March 2025",
    club: "FORCE",
    interIIIT: "No",
    teamLimit: "Individual",
    tag: ["recruitment", "coding", "aptitude"],
    difficulty: "Competitive",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/p/hired-or-fired-indian-institute-of-information-technology-iiit-una-1434917",
  },
  {
    id: "16",
    name: "Coder's Face Off",
    overview:
      "A frontend development competition where participants convert Figma designs into functional web or mobile interfaces, with live twists during the contest.",
    image: "/events/event17.png",
    date: "3rd April 2025",
    time: "3:00 PM - 5:30 PM",
    regDate: "30th March 2025",
    club: "FORCE",
    interIIIT: "Yes",
    teamLimit: "Individual",
    tag: ["frontend", "coding", "design"],
    difficulty: "Challenging",
    prizePool: "₹5,000 + Trophies & Goodies",
    unstopLink: "https://unstop.com/hackathons/coders-faceoff-indian-institute-of-information-technology-iiit-una-1435066",
  },
  {
    id: "17",
    name: "Robo-Drive",
    overview:
      "A thrilling robotic car race where teams design, assemble, and program high-speed robotic cars to navigate a challenging course in elimination and final rounds.",
    image: "/events/event6.png",
    date: "4th April 2025",
    time: "6:00 pm - 8:30 pm",
    regDate: "31st March 2025",
    club: "AAVESH",
    interIIIT: "Yes",
    teamLimit: "Maximum 4 members per team",
    tag: ["robotics", "racing", "innovation"],
    difficulty: "Adrenaline-Packed",
    prizePool: "₹10,000 + Trophies & Goodies",
    unstopLink: "https://unstop.com/competitions/robo-drive-indian-institute-of-information-technology-iiit-una-1434573",
  },
  {
    id: "18",
    name: "UCPC",
    overview:
      "Una Competitive Programming Contest is a team-based competitive programming contest where teams solve algorithmic challenges on a local judge system, with rankings determined by problem-solving speed and accuracy.",
    image: "/events/event18.png",
    date: "4th April 2025",
    time: "9:30 pm onwards",
    regDate: "31st March 2025",
    club: "FORCE",
    interIIIT: "No",
    teamLimit: "3 members per team",
    tag: ["programming", "coding", "competition"],
    difficulty: "Brain-Burning",
    prizePool: "Trophies & Certificates",
    unstopLink: "https://unstop.com/p/una-competitive-programming-contest-ucpc-indian-institute-of-information-technology-iiit-una-1434713",
  },
];


export const TeamData = [
  {
    name: "Gurpreet Kaur",
    img: "/Team/gurpreetKaur.jpeg",
    club: "Faculty",
    team: "Cooridnator",
  },
  {
    name: "Nishtha Hooda",
    img: "/Team/nishthaHooda.jpeg",
    club: "Faculty",
    team: "Cooridnator",
  },
  {
    name: "Prakhar Jaiswal",
    img: "/Team/prakharsir.jpeg",
    club: "Aavesh",
    team: "President",
  },
  {
    name: "Vansh Verma",
    img: "/Team/vansh.jpg",
    club: "Force",
    team: "Devteam",
  },
  {
    name: "Pranav Shrivastava",
    img: "/Team/pranav-shri.jpeg",
    club: "EIC",
    team: "Devteam",
  },
  {
    name: "Pranav Garg",
    img: "/Team/pranav-garg.jpeg",
    club: "Aavesh",
    team: "Devteam",
  },
  {
    name: "Srishti Sethi",
    img: "/Team/shristi.jpeg",
    club: "Force",
    team: "Devteam",
  },
  { name: "Aditya Goyal", img: "/Team/aditya.jpeg", club: "Force", team: "Devteam" },
];
